- project:
    templates:
      - openstack-python36-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke-py3:
            required-projects: &neutron-plugin-version-stein
              - name: openstack/neutron-tempest-plugin
                override-checkout: 1.0.0
        - networking-nuage-tempest-smoke-py3-vsdipam:
            required-projects: *neutron-plugin-version-stein

    gate:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke-py3:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-smoke-py3-vsdipam:
            required-projects: *neutron-plugin-version-stein

    experimental:
      jobs:
        - networking-nuage-vtep-vxlan:
            required-projects: *neutron-plugin-version-stein
    virtio:
      jobs:
        - networking-nuage-tempest-virtio-py3:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-virtio-py3-vsdipam:
            required-projects: *neutron-plugin-version-stein
    sriov:
      jobs:
        - networking-nuage-tempest-sriov:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-sriov-flat-vlan:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-sriov-vsdipam:
            required-projects: *neutron-plugin-version-stein
    baremetal:
      jobs:
        - networking-nuage-tempest-baremetal:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-baremetal-vsdipam:
            required-projects: *neutron-plugin-version-stein
    full:
      jobs:
        - networking-nuage-tempest-virtio-py3:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-virtio-py3-vsdipam:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-sriov:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-sriov-vsdipam:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-sriov-flat-vlan:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-baremetal:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-baremetal-vsdipam:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-scenario:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-scenario-vsdipam:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-vtep-vlan-upstream:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-vtep-vlan-nuage:
            required-projects: *neutron-plugin-version-stein
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp:
            required-projects: *neutron-plugin-version-stein
    octavia:
      jobs:
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros-ipv6.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/stein/amphora-x64-haproxy.qcow2"
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros-ipv6.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/stein/amphora-x64-haproxy.qcow2"
            required-projects: *neutron-plugin-version-stein
    sfc:
      jobs:
        - legacy-tempest-aio-sfc:
            required-projects: *neutron-plugin-version-stein
    rally:
      jobs:
        - networking-nuage-rally-task
    switchdev:
      jobs:
        - networking-nuage-tempest-api-switchdev:
            required-projects: *neutron-plugin-version-stein
    cli:
      jobs:
        - networking-nuage-tempest-cli:
            required-projects: *neutron-plugin-version-stein
    aggregateflows:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            required-projects: *neutron-plugin-version-stein
    scenario:
      jobs:
        - networking-nuage-tempest-scenario:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-scenario-vsdipam:
            required-projects: *neutron-plugin-version-stein
    scale:
      jobs:
        - networking-nuage-tempest-scale:
            required-projects: *neutron-plugin-version-stein
    upstream:
      jobs:
        - tempest-full-py3:
            required-projects: *neutron-plugin-version-stein
        - tempest-full-py3-vsdipam:
            required-projects: *neutron-plugin-version-stein
    periodic:
      jobs:
        - networking-nuage-tempest-virtio-py3:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-sriov:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-baremetal:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-scenario:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-cli:
            required-projects: *neutron-plugin-version-stein
        - tempest-full-py3:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-api-switchdev:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-vtep-vlan-upstream:
            required-projects: *neutron-plugin-version-stein
    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-sriov-flat-vlan:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-rally-task
        - networking-nuage-vtep-vxlan:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-vtep-vlan-nuage:
            required-projects: *neutron-plugin-version-stein
    periodic-sunday:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-scale:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros-ipv6.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/stein/amphora-x64-haproxy.qcow2"
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros-ipv6.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/stein/amphora-x64-haproxy.qcow2"
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-virtio-py3-vsdipam:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-sriov-vsdipam:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-baremetal-vsdipam:
            required-projects: *neutron-plugin-version-stein
        - networking-nuage-tempest-scenario-vsdipam:
            required-projects: *neutron-plugin-version-stein
        - tempest-full-py3-vsdipam:
            required-projects: *neutron-plugin-version-stein


- job:
    name: networking-nuage-rally-task
    parent: rally-task-at-devstack
    branches: ^(?!stable/(newton|ocata|pike)).*$
    nodeset: openstack-single-node
    required-projects:
      - name: opendev.org/openstack/devstack
      - name: opendev.org/openstack/devstack-gate
      - name: opendev.org/openstack/rally
      - name: opendev.org/openstack/rally-openstack
      - name: OpenStack/nuage-openstack-neutron
    pre-run: playbooks/pre-run.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    vars:
      use_pypi: true
      nuage_fip_range: "172.{{ 255 | random }}.{{ 255 | random }}"
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
        nuage-openstack-neutron: https://github.com/nuagenetworks/nuage-openstack-neutron.git
      devstack_services:
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
      devstack_localrc:
        FLOATING_RANGE: "{{ nuage_fip_range }}.0/24"
        PUBLIC_NETWORK_GATEWAY: "{{ nuage_fip_range }}.1"
        Q_PLUGIN: ml2
        Q_USE_PROVIDERNET_FOR_PUBLIC: False
        Q_ML2_PLUGIN_EXT_DRIVERS: nuage_subnet,nuage_port,port_security,nuage_network
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: nuage
        Q_ML2_PLUGIN_TYPE_DRIVERS: vxlan
        NUAGE_VSD_DEF_NETPART_NAME: "NuageCi-{{ 1000000 | random }}"
        NUAGE_FIP_UNDERLAY: True
        NUAGE_USE_METADATA: True
        NUAGE_METADATA_SHARED_SECRET: sharedsecret
        NUAGE_PAT: legacy_disabled
        OVS_BRIDGE: alubr0
      rally_task: rally-jobs/nuage-openstack-neutron.yaml
    timeout: 7800

- job:
    name: legacy-tempest-aio-base
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: ml2
      python3: False
      branch_override: default
    timeout: 10800
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    vars:
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-client  # used by nuage-openstack-neutronclient
    parent: legacy-tempest-aio-base
    vars:
      job_flavor: neutronclient
    timeout: 9000
