- project:

    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky

    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky

    periodic:
      jobs:
        - networking-nuage-tempest-virtio-5.4:
            override-checkout: stable/rocky
            required-projects: &required-projects-rocky-54
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
              - name: OpenStack/nuage-openstack-neutronclient
                override-checkout: 5.4/rocky
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.9.0
        - networking-nuage-tempest-sriov-5.4:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky-54
        - networking-nuage-tempest-baremetal-5.4:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky-54
        - networking-nuage-tempest-cli-5.4:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky-54
        - networking-nuage-tempest-scenario-5.4:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky-54
        - tempest-full-5.4:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky-54

    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp-5.4:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky-54
        - networking-nuage-tempest-sriov-flat-vlan-5.4:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky-54

    periodic-sunday:
      jobs:
        - networking-nuage-tempest-lbaas-5.4:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky-54
        - networking-nuage-fwaas-v1:
            override-checkout: stable/rocky
            vars:
              vsp_release: '5.4'
            required-projects: *required-projects-rocky-54

    fwaas:
      jobs:
        - networking-nuage-fwaas-v1:
            override-checkout: stable/rocky
            vars:
              vsp_release: '5.4'
            required-projects: *required-projects-rocky-54