- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py35:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py35:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
    periodic:
      jobs:
        - networking-nuage-tempest-virtio-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - networking-nuage-tempest-scenario-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - tempest-full-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky

    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - networking-nuage-tempest-sriov-flat-vlan-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky

    periodic-sunday:
      jobs:
        - networking-nuage-tempest-sriov-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - networking-nuage-tempest-baremetal-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - networking-nuage-tempest-cli-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
