- project:

    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - openstack-tox-py35:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens

    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - openstack-tox-py35:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens

    periodic:
      jobs:
        - networking-nuage-tempest-virtio-5.4:
            override-checkout: stable/queens
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens
        - networking-nuage-tempest-sriov-5.4:
            override-checkout: stable/queens
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens
        - networking-nuage-tempest-baremetal-5.4:
            override-checkout: stable/queens
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens
        - networking-nuage-tempest-cli-5.4:
            override-checkout: stable/queens
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens
        - networking-nuage-tempest-scenario-5.4:
            override-checkout: stable/queens
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens
        - tempest-full-5.4:
            override-checkout: stable/queens
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens

    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp-5.4:
            override-checkout: stable/queens
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens'
        - networking-nuage-tempest-sriov-flat-vlan-5.4:
            override-checkout: stable/queens
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens'
