- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              opendev.org/openstack/neutron
        - openstack-tox-py27:
            required-projects:
              opendev.org/openstack/neutron
        - openstack-tox-py36:
            required-projects:
              opendev.org/openstack/neutron
        - networking-nuage-tempest-smoke:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              opendev.org/openstack/neutron
        - openstack-tox-py27:
            required-projects:
              opendev.org/openstack/neutron
        - openstack-tox-py36:
            required-projects:
              opendev.org/openstack/neutron
        - networking-nuage-tempest-smoke:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    virtio:
      jobs:
        - networking-nuage-tempest-virtio:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    sriov:
      jobs:
        - networking-nuage-tempest-sriov:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-sriov-flat-vlan:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    baremetal:
      jobs:
        - networking-nuage-tempest-baremetal:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    full:
      jobs:
        - networking-nuage-tempest-virtio:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-sriov:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-sriov-flat-vlan:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-baremetal:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-scenario:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    fwaas:
      jobs:
        - legacy-tempest-aio-fwaas
    octavia:
      jobs:
        - networking-nuage-octavia:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/octavia-tempest-plugin /opt/stack/nuage-octavia-tempest-plugin"'
        - networking-nuage-octavia-standby:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/octavia-tempest-plugin /opt/stack/nuage-octavia-tempest-plugin"'
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    rally:
      jobs:
        - networking-nuage-rally-task:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
    switchdev:
      jobs:
        - networking-nuage-tempest-sriov-switchdev:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    cli:
      jobs:
        - networking-nuage-tempest-cli:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    aggregateflows:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    scenario:
      jobs:
        - networking-nuage-tempest-scenario:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    scale:
      jobs:
        - networking-nuage-tempest-scale:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    upstream:
      jobs:
        - tempest-full:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    periodic:
      jobs:
        - networking-nuage-tempest-virtio:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
        - networking-nuage-tempest-scenario:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
        - tempest-full:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    periodic-saturday:
      jobs:
        - networking-nuage-tempest-baremetal:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-cli:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-sriov:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-sriov-flat-vlan:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    periodic-sunday:
      jobs:
        - networking-nuage-tempest-qdhcp:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
        - networking-nuage-tempest-aggregateflows:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-scale:
            nodeset: openstack-single-node-xenial
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    nodeset: devstack-single-node
    vars:
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-fwaas
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-fwaas/run.yaml
    post-run: playbooks/tempest-aio-fwaas/post.yaml
    nodeset: devstack-single-node
    vars:
      job_flavor: fwaas
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/neutron-fwaas
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-client  # used by nuage-openstack-neutronclient
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    nodeset: devstack-single-node
    vars:
      job_flavor: neutronclient
      python3: False
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/neutron-tempest-plugin
      - openstack/tempest

