- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron
