- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
    check:
      jobs:
        - networking-nuage-tempest-smoke:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
        - networking-nuage-tempest-smoke-py3:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    gate:
      jobs:
        - networking-nuage-tempest-smoke:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
        - networking-nuage-tempest-smoke-py3:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    full:
      jobs:
        - networking-nuage-tempest-full:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    sriov:
      jobs:
        - networking-nuage-tempest-sriov:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        - networking-nuage-tempest-sriov-flat-vlan:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    fwaas:
      jobs:
        - legacy-tempest-aio-fwaas
    octavia:
      jobs:
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/octavia-tempest-plugin /opt/stack/nuage-octavia-tempest-plugin"'
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/octavia-tempest-plugin /opt/stack/nuage-octavia-tempest-plugin"'
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    rally:
      jobs:
        - networking-nuage-rally-task
    switchdev:
      jobs:
        - networking-nuage-tempest-sriov-switchdev:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
    upstream:
      jobs:
        - tempest-full-py3:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
    periodic:
      jobs:
        - networking-nuage-tempest-full-py3:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
        - tempest-full-py3:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    vars:
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-fwaas
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-fwaas/run.yaml
    post-run: playbooks/tempest-aio-fwaas/post.yaml
    vars:
      job_flavor: fwaas
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/neutron-fwaas
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-client  # used by nuage-openstack-neutronclient
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: neutronclient
      python3: False
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/neutron-tempest-plugin
      - openstack/tempest

