- project:
    templates:
      - openstack-python-jobs
    check:
      jobs:
        - networking-nuage-tempest-smoke:
            vars: &required-vars-rocky
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
            required-projects: &required-projects-rocky
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.9.0
        - networking-nuage-tempest-smoke-py3-vsdipam:
            vars: *required-vars-rocky
            required-projects: *required-projects-rocky

    gate:
      jobs:
        - networking-nuage-tempest-smoke:
            vars: *required-vars-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-smoke-vsdipam:
            required-projects: *required-projects-rocky

    experimental:
      jobs:
        - networking-nuage-vtep-vxlan:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
            required-projects: *required-projects-rocky
    virtio:
      jobs:
        - networking-nuage-tempest-virtio:
            vars: *required-vars-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-virtio-vsdipam:
            vars: *required-vars-rocky
            required-projects: *required-projects-rocky
    sriov:
      jobs:
        - networking-nuage-tempest-sriov:
            vars: &required-vars-nuage-only-rocky
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-sriov-flat-vlan:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-sriov-vsdipam:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
    baremetal:
      jobs:
        - networking-nuage-tempest-baremetal:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-baremetal-vsdipam:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
    full:
      jobs:
        - networking-nuage-tempest-virtio:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-virtio-vsdipam:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-sriov:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-sriov-vsdipam:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-sriov-flat-vlan:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-baremetal:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-baremetal-vsdipam:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-scenario:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-scenario-vsdipam:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-vtep-vlan-upstream:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-vtep-vlan-nuage:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
    fwaas:
      jobs:
        - networking-nuage-fwaas-v1:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky
    octavia:
      jobs:
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/octavia-tempest-plugin /opt/stack/nuage-octavia-tempest-plugin"'
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros-ipv6.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/rocky/amphora-x64-haproxy.qcow2"
            required-projects: *required-projects-rocky
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/octavia-tempest-plugin /opt/stack/nuage-octavia-tempest-plugin"'
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros-ipv6.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/rocky/amphora-x64-haproxy.qcow2"
            required-projects: *required-projects-rocky
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    rally:
      jobs:
        - networking-nuage-rally-task:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects: *required-projects-rocky
    switchdev:
      jobs:
        - networking-nuage-tempest-api-switchdev:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects: *required-projects-rocky
    cli:
      jobs:
        - networking-nuage-tempest-cli:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects: *required-projects-rocky
    aggregateflows:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects: *required-projects-rocky
    scenario:
      jobs:
        - networking-nuage-tempest-scenario:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-scenario-vsdipam:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
    scale:
      jobs:
        - networking-nuage-tempest-scale:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
    upstream:
      jobs:
        - tempest-full:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/neutron-tempest-plugin"'
            required-projects: *required-projects-rocky
        - tempest-full-vsdipam:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/neutron-tempest-plugin"'
            required-projects: *required-projects-rocky
    periodic:
      jobs:
        - networking-nuage-tempest-virtio:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-sriov:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-baremetal:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-cli:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-scenario:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - tempest-full:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/neutron-tempest-plugin"'
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-api-switchdev:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-vtep-vlan-upstream:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
            required-projects: *required-projects-rocky
    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-sriov-flat-vlan:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-rally-task:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-fwaas-v1:
            override-checkout: stable/rocky
            required-projects: *required-projects-rocky
        - networking-nuage-vtep-vxlan:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-vtep-vlan-nuage:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
            required-projects: *required-projects-rocky
    periodic-sunday:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-scale:
            vars: *required-vars-nuage-only-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros-ipv6.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/rocky/amphora-x64-haproxy.qcow2"
            required-projects: *required-projects-rocky
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros-ipv6.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/rocky/amphora-x64-haproxy.qcow2"
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-virtio-vsdipam:
            vars: *required-vars-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-sriov-vsdipam:
            vars: *required-vars-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-baremetal-vsdipam:
            vars: *required-vars-rocky
            required-projects: *required-projects-rocky
        - networking-nuage-tempest-scenario-vsdipam:
            vars: *required-vars-rocky
            required-projects: *required-projects-rocky
        - tempest-full-vsdipam:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/neutron-tempest-plugin"'
            required-projects: *required-projects-rocky


- job:
    name: networking-nuage-rally-task
    parent: rally-task-at-devstack
    branches: ^(?!stable/(newton|ocata|pike)).*$
    nodeset: openstack-single-node
    required-projects:
      - name: opendev.org/openstack/devstack
      - name: opendev.org/openstack/devstack-gate
      - name: opendev.org/openstack/rally
      - name: opendev.org/openstack/rally-openstack
      - name: OpenStack/nuage-openstack-neutron
    pre-run: playbooks/pre-run.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    vars:
      use_pypi: true
      nuage_fip_range: "172.{{ 255 | random }}.{{ 255 | random }}"
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
        nuage-openstack-neutron: https://github.com/nuagenetworks/nuage-openstack-neutron.git
      devstack_services:
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
      devstack_localrc:
        FLOATING_RANGE: "{{ nuage_fip_range }}.0/24"
        PUBLIC_NETWORK_GATEWAY: "{{ nuage_fip_range }}.1"
        Q_PLUGIN: ml2
        Q_USE_PROVIDERNET_FOR_PUBLIC: False
        Q_ML2_PLUGIN_EXT_DRIVERS: nuage_network,nuage_subnet,nuage_port,port_security
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: nuage
        Q_ML2_PLUGIN_TYPE_DRIVERS: vxlan
        NUAGE_VSD_DEF_NETPART_NAME: "NuageCi-{{ 1000000 | random }}"
        NUAGE_FIP_UNDERLAY: True
        NUAGE_USE_METADATA: True
        NUAGE_METADATA_SHARED_SECRET: sharedsecret
        NUAGE_PAT: legacy_disabled
        OVS_BRIDGE: alubr0
      rally_task: rally-jobs/nuage-openstack-neutron.yaml
    timeout: 7800

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    vars:
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-client  # used by nuage-openstack-neutronclient
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    nodeset: devstack-single-node
    vars:
      job_flavor: neutronclient
      python3: False
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - name: openstack/neutron-tempest-plugin
        override-checkout: 0.9.0
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/neutron-tempest-plugin
      - openstack/tempest
