- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py35:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
        - openstack-tox-py35:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/rocky
    full:
      jobs:
        - networking-nuage-tempest-virtio-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - networking-nuage-tempest-sriov-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - networking-nuage-tempest-sriov-flat-vlan-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky'
        - networking-nuage-tempest-baremetal-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - networking-nuage-tempest-scenario-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
    sriov:
      jobs:
        - networking-nuage-tempest-sriov-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
    agent:
      jobs:
        - legacy-tempest-aio-agent
    fwaas:
      jobs:
        - legacy-tempest-aio-fwaas
    octavia:
      jobs:
        - legacy-tempest-aio-octavia
        - legacy-tempest-aio-octavia-standby
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    rally:
      jobs:
        - legacy-tempest-aio-rally
    switchdev:
      jobs:
        - legacy-tempest-aio-switchdev
    upstream:
      jobs:
        - tempest-full-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
    periodic:
      jobs:
        - networking-nuage-tempest-full-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky
        - tempest-full-5.4:
            override-checkout: stable/rocky
            required-projects:
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/rocky

- job:
    name: legacy-tempest-aio-sriov
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sriov/run.yaml
    post-run: playbooks/tempest-aio-sriov/post.yaml
    vars:
      job_flavor: sriov
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/networking-testsriov
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-sriov-allow-existing-flat-vlan
    parent: legacy-tempest-aio-sriov
    vars:
      job_flavor: sriov-allow-existing-flat-vlan

- job:
    name: legacy-tempest-aio-agent
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: agent-nv
      python3: False
      branch_override: default
    timeout: 14400
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-fwaas
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-fwaas/run.yaml
    post-run: playbooks/tempest-aio-fwaas/post.yaml
    vars:
      job_flavor: fwaas
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/devstack-gate
      - openstack/neutron-fwaas
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-octavia
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-octavia/run.yaml
    post-run: playbooks/tempest-aio-octavia/post.yaml
    vars:
      job_flavor: octavia
      branch_override: default
      tempest_concurrency: ''

    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - OpenStack/nuage-octavia-tempest-plugin
      - openstack/devstack-gate
      - openstack/octavia
      - openstack/octavia-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-octavia-standby
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-octavia/run.yaml
    post-run: playbooks/tempest-aio-octavia/post.yaml
    vars:
      job_flavor: octavia-standby
      branch_override: default
      tempest_concurrency: 1
    timeout: 14400
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - OpenStack/nuage-octavia-tempest-plugin
      - openstack/devstack-gate
      - openstack/octavia
      - openstack/octavia-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-lbaas
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-lbaas/run.yaml
    post-run: playbooks/tempest-aio-lbaas/post.yaml
    vars:
      job_flavor: lbaas
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/devstack-gate
      - openstack/neutron-lbaas
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    vars:
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/devstack-gate
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-switchdev
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-switchdev/run.yaml
    post-run: playbooks/tempest-aio-switchdev/post.yaml
    vars:
      job_flavor: switchdev
      branch_override: default
    timeout: 14400
    required-projects:
      - OpenStack/networking-testsriov
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/placement
      - openstack/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-rally
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-rally/run.yaml
    post-run: playbooks/tempest-aio-rally/post.yaml
    vars:
      job_flavor: rally
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - openstack/devstack-gate
      - openstack/rally
      - openstack/rally-openstack

- job:
    name: legacy-tempest-aio-client  # used by nuage-openstack-neutronclient
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: neutronclient
      python3: False
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest
