- project:
    templates:
      - openstack-python35-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke-py3
    gate:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-smoke-py3
    full:
      jobs:
        - networking-nuage-tempest-full
    sriov:
      jobs:
        - networking-nuage-tempest-sriov
        - networking-nuage-tempest-sriov-flat-vlan
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp
    octavia:
      jobs:
        - networking-nuage-octavia
        - networking-nuage-octavia-standby
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    rally:
      jobs:
        - networking-nuage-rally-task
    switchdev:
      jobs:
        - networking-nuage-tempest-sriov-switchdev
    upstream:
      jobs:
        - tempest-full-py3
    experimental:
      jobs:
        - networking-nuage-tempest-smoke-py3:
            nodeset: openstack-single-node-rhel7
    periodic:
      jobs:
        - networking-nuage-tempest-full-py3
        - tempest-full-py3

- job:
    name: legacy-tempest-aio-base
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: ml2
      python3: False
      branch_override: default
    timeout: 10800
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    vars:
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-client  # used by nuage-openstack-neutronclient
    parent: legacy-tempest-aio-base
    vars:
      job_flavor: neutronclient
    timeout: 9000

