- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron
        - openstack-tox-py35:
            required-projects:
              - openstack/neutron
        - legacy-tempest-aio-ml2:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^nuage_neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
              - ^tox.ini$
              - ^COMMIT_MSG$
        - legacy-tempest-aio-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^nuage_neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
              - ^tox.ini$
                ^COMMIT_MSG$
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/neutron
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron
        - openstack-tox-py35:
            required-projects:
              - openstack/neutron
        - legacy-tempest-aio-ml2:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^nuage_neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
              - ^tox.ini$
              - ^COMMIT_MSG$
        - legacy-tempest-aio-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^nuage_neutron/tests/unit/.*$
              - ^setup.cfg$
              - ^specs/.*$
              - ^tox.ini$
                ^COMMIT_MSG$
    full:
      jobs:
        - legacy-tempest-aio-full
        - legacy-tempest-aio-full-py3
    sriov:
      jobs:
        - legacy-tempest-aio-sriov
    agent:
      jobs:
        - legacy-tempest-aio-agent
    fwaas:
      jobs:
        - legacy-tempest-aio-fwaas
    octavia:
      jobs:
        - legacy-tempest-aio-octavia
        - legacy-tempest-aio-octavia-standby
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    rally:
      jobs:
        - legacy-tempest-aio-rally
    switchdev:
      jobs:
        - legacy-tempest-aio-switchdev
    upstream:
      jobs:
        - legacy-tempest-aio-upstream
    periodic:
      jobs:
        - legacy-tempest-aio-full:
            branches:
              - stable/newton
              - stable/ocata
              - stable/pike
              - stable/queens
              - stable/rocky
              - master
        - legacy-tempest-aio-legacy-pat:  # using legacy PAT model
            #                            -- hoped for to remove soon (6.0)
            branches:
              - stable/newton
              - stable/queens  # limit to few branches
        - legacy-tempest-aio-upstream:
            branches:
              - stable/newton
              - stable/ocata
              - stable/pike
              - stable/queens
              - stable/rocky
              - master

- job:
    name: legacy-tempest-aio-ml2
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: ml2
      python3: False
      branch_override: default
    timeout: 10800
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-full
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: full
      python3: False
      branch_override: default
    timeout: 14400
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-legacy-pat
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: legacy-pat  # legacy PAT model
      python3: False
      branch_override: default
    timeout: 14400
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-sriov
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sriov/run.yaml
    post-run: playbooks/tempest-aio-sriov/post.yaml
    vars:
      job_flavor: sriov
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/networking-testsriov
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-agent
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: agent-nv
      python3: False
      branch_override: default
    timeout: 14400
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-fwaas
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-fwaas/run.yaml
    post-run: playbooks/tempest-aio-fwaas/post.yaml
    vars:
      job_flavor: fwaas
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-fwaas
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-octavia
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-octavia/run.yaml
    post-run: playbooks/tempest-aio-octavia/post.yaml
    vars:
      job_flavor: octavia
      branch_override: default
      tempest_concurrency: ''

    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - OpenStack/nuage-octavia-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/octavia
      - openstack/octavia-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-octavia-standby
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-octavia/run.yaml
    post-run: playbooks/tempest-aio-octavia/post.yaml
    vars:
      job_flavor: octavia-standby
      branch_override: default
      tempest_concurrency: 1
    timeout: 14400
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - OpenStack/nuage-octavia-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/octavia
      - openstack/octavia-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-lbaas
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-lbaas/run.yaml
    post-run: playbooks/tempest-aio-lbaas/post.yaml
    vars:
      job_flavor: lbaas
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-lbaas
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    vars:
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/networking-sfc
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-switchdev
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-switchdev/run.yaml
    post-run: playbooks/tempest-aio-switchdev/post.yaml
    vars:
      job_flavor: switchdev
      branch_override: default
    timeout: 14400
    required-projects:
      - OpenStack/networking-testsriov
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/placement
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-rally
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-rally/run.yaml
    post-run: playbooks/tempest-aio-rally/post.yaml
    vars:
      job_flavor: rally
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - openstack-infra/devstack-gate
      - openstack/rally
      - openstack/rally-openstack

- job:
    name: legacy-tempest-aio-upstream
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: neutron
      python3: False
      branch_override: default
    timeout: 10800
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-client  # used by nuage-openstack-neutronclient
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: neutronclient
      python3: False
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/tempest

- job:
    name: legacy-tempest-aio-py3
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: ml2
      python3: True
      branch_override: default
    timeout: 10800
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: legacy-tempest-aio-full-py3
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-ml2/run.yaml
    post-run: playbooks/tempest-aio-ml2/post.yaml
    vars:
      job_flavor: ml2-full
      python3: True
      branch_override: default
    timeout: 14400
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack-infra/devstack-gate
      - openstack/neutron-tempest-plugin
      - openstack/placement
      - openstack/python-neutronclient
      - openstack/tempest
