- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens
        - openstack-tox-py27:
            required-projects:
              - name: opendev.org/openstack/neutron
                override-checkout: stable/queens

    periodic:
      jobs:
        - networking-nuage-tempest-virtio-5.4:
            override-checkout: stable/queens
            required-projects: &required-projects
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 5.4/queens
              - name: OpenStack/nuage-openstack-neutronclient
                override-checkout: 5.4/queens
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
        - networking-nuage-tempest-sriov-5.4:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-baremetal-5.4:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-cli-5.4:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-scenario-5.4:
            override-checkout: stable/queens
            required-projects: *required-projects
        - tempest-full-5.4:
            override-checkout: stable/queens
            required-projects: *required-projects

    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp-5.4:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-flat-vlan-5.4:
            override-checkout: stable/queens
            required-projects: *required-projects

    periodic-sunday:
      jobs:
        - networking-nuage-tempest-lbaas-5.4:
            override-checkout: stable/queens
            required-projects: *required-projects
        - networking-nuage-fwaas-v1:
            override-checkout: stable/queens
            vars:
              vsp_release: '5.4'
            required-projects: *required-projects

    fwaas:
      jobs:
        - networking-nuage-fwaas-v1:
            override-checkout: stable/queens
            vars:
              vsp_release: '5.4'
            required-projects: *required-projects