- project:
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              opendev.org/openstack/neutron
        - openstack-tox-py27:
            required-projects:
              opendev.org/openstack/neutron
        - networking-nuage-tempest-smoke:
            vars: &vars
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
            required-projects: &required-projects
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
        - networking-nuage-tempest-smoke-vsdipam:
            vars: *vars
            required-projects: *required-projects

    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              opendev.org/openstack/neutron
        - openstack-tox-py27:
            required-projects:
              opendev.org/openstack/neutron
        - networking-nuage-tempest-smoke:
            vars: *vars
            required-projects: *required-projects
        - networking-nuage-tempest-smoke-vsdipam:
            vars: *vars
            required-projects: *required-projects

    virtio:
      jobs:
        - networking-nuage-tempest-virtio:
            vars: *vars
            required-projects: *required-projects
        - networking-nuage-tempest-virtio-vsdipam:
            vars: *vars
            required-projects: *required-projects
    sriov:
      jobs:
        - networking-nuage-tempest-sriov:
            vars: &vars-nuage
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-flat-vlan:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
    baremetal:
      jobs:
        - networking-nuage-tempest-baremetal:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-baremetal-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
    full:
      jobs:
        - networking-nuage-tempest-virtio:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-virtio-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-sriov:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-flat-vlan:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-baremetal:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-baremetal-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-scenario:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-scenario-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-vtep-vlan-upstream:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-vtep-vlan-nuage:
            vars: *vars-nuage
            required-projects: *required-projects
    agent:
      jobs:
        - networking-nuage-tempest-qdhcp:
            vars: *vars-nuage
            required-projects: *required-projects
    fwaas:
      jobs:
        - networking-nuage-fwaas-v1:
            required-projects: *required-projects
    octavia:
      jobs:
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/queens/amphora-x64-haproxy.qcow2"
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/queens/amphora-x64-haproxy.qcow2"
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
    sfc:
      jobs:
        - legacy-tempest-aio-sfc
    rally:
      jobs:
        - networking-nuage-rally-task:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
    switchdev:
      jobs:
        - networking-nuage-tempest-api-switchdev:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
    cli:
      jobs:
        - networking-nuage-tempest-cli:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
    aggregateflows:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
    scenario:
      jobs:
        - networking-nuage-tempest-scenario:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-scenario-rhel:
            vars: *vars-nuage
            required-projects: *required-projects
    scale:
      jobs:
        - networking-nuage-tempest-scale:
            vars: *vars-nuage
            required-projects: *required-projects
    upstream:
      jobs:
        - tempest-full:
            vars:
              devstack_localrc:
                TEMPEST_PLUGINS: '"/opt/stack/neutron-tempest-plugin"'
            required-projects: *required-projects
        - tempest-full-vsdipam:
              vars:
                devstack_localrc:
                  TEMPEST_PLUGINS: '"/opt/stack/neutron-tempest-plugin"'
              required-projects: *required-projects

    periodic:
      jobs:
        - networking-nuage-tempest-virtio:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-sriov:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-baremetal:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-cli:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-scenario:
            vars: *vars-nuage
            required-projects: *required-projects
        - tempest-full:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                TEMPEST_PLUGINS: '"/opt/stack/neutron-tempest-plugin"'
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
        - networking-nuage-tempest-api-switchdev:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-vtep-vlan-upstream:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
    periodic-saturday:
      jobs:
        - networking-nuage-tempest-qdhcp:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-flat-vlan:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-rally-task:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-fwaas-v1:
            required-projects: *required-projects
        - networking-nuage-vtep-vxlan:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-vtep-vlan-nuage:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
    periodic-sunday:
      jobs:
        - networking-nuage-tempest-aggregateflows:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-scale:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-smoke-multiversion:
            required-projects: *required-projects
        - networking-nuage-octavia:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/queens/amphora-x64-haproxy.qcow2"
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
        - networking-nuage-octavia-standby:
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
                IMAGE_URLS: "http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/cirros.qcow2, http://openstack-infra.an.nuagenetworks.net/nuage-glance-images/octavia/queens/amphora-x64-haproxy.qcow2"
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
        - networking-nuage-tempest-virtio-py3-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-sriov-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-baremetal-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
        - networking-nuage-tempest-scenario-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects
        - tempest-full-py3-vsdipam:
            vars: *vars-nuage
            required-projects: *required-projects


- job:
    name: networking-nuage-rally-task
    parent: rally-task-at-devstack
    branches: ^(?!stable/(newton|ocata|pike)).*$
    nodeset: openstack-single-node
    required-projects:
      - name: opendev.org/openstack/devstack
      - name: opendev.org/openstack/devstack-gate
      - name: opendev.org/openstack/rally
      - name: opendev.org/openstack/rally-openstack
      - name: OpenStack/nuage-openstack-neutron
    pre-run: playbooks/pre-run.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tools/.*$
      - ^tox.ini$
    vars:
      use_pypi: true
      vsp_release: '20.5'
      nuage_fip_range: "172.{{ 255 | random }}.{{ 255 | random }}"
      devstack_plugins:
        rally-openstack: https://opendev.org/openstack/rally-openstack
        nuage-openstack-neutron: https://github.com/nuagenetworks/nuage-openstack-neutron.git
      devstack_services:
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
      devstack_localrc:
        FLOATING_RANGE: "{{ nuage_fip_range }}.0/24"
        PUBLIC_NETWORK_GATEWAY: "{{ nuage_fip_range }}.1"
        Q_PLUGIN: ml2
        Q_USE_PROVIDERNET_FOR_PUBLIC: False
        Q_ML2_PLUGIN_EXT_DRIVERS: nuage_network,nuage_subnet,nuage_port,port_security
        Q_ML2_PLUGIN_MECHANISM_DRIVERS: nuage
        Q_ML2_PLUGIN_TYPE_DRIVERS: vxlan
        NUAGE_VSD_DEF_NETPART_NAME: "NuageCi-{{ 1000000 | random }}"
        NUAGE_FIP_UNDERLAY: True
        NUAGE_USE_METADATA: True
        NUAGE_METADATA_SHARED_SECRET: sharedsecret
        NUAGE_PAT: legacy_disabled
        OVS_BRIDGE: alubr0
      rally_task: rally-jobs/nuage-openstack-neutron.yaml
    timeout: 7800

- job:
    name: legacy-tempest-aio-sfc
    parent: legacy-dsvm-base
    run: playbooks/tempest-aio-sfc/run.yaml
    post-run: playbooks/tempest-aio-sfc/post.yaml
    nodeset: devstack-single-node
    vars:
      vsp_release: '20.5'
      job_flavor: sfc
      branch_override: default
    timeout: 9000
    required-projects:
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
      - OpenStack/nuage-tempest-plugin
      - openstack/networking-sfc
      - name: openstack/neutron-tempest-plugin
        override-checkout: 0.3.0
      - openstack/python-neutronclient
      - openstack/tempest

- job:
    name: networking-nuage-tempest-smoke-multiversion
    parent: networking-nuage-tempest-smoke
    vars:
      vsp_release: 5.4
      ci_vsp_name: ci-vsp-multiversion
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin /opt/stack/neutron-tempest-plugin"'
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            nuage_sut:
              nuage_pat_legacy: disabled
      tempest_test_regex: '^(nuage_tempest_plugin|tempest\.api\.network|neutron_tempest_plugin\.(api|scenario))\..*\[(?=.*smoke)'
      tempest_test_blacklist: "{{devstack_base_dir}}/nuage-tempest-plugin/tempest-blacklist.txt"
    required-projects:
      - name: OpenStack/nuage-openstack-neutron
        override-checkout: '5.4/queens'
      - name: OpenStack/nuage-tempest-plugin
        override-checkout: '5.4'
      - name: openstack/neutron-tempest-plugin
        override-checkout: 0.3.0
